### ISSUE TITLE
Needs a readme.md

### ISSUE THREAD

**Issue by julianpoy** [torch2424/Fight#1]
I'd love to know what this project is but without a readme.md I can't read about your fantabulous project details!

**Comment by torch2424** [comment]
@julianpoy your mom needs a readme.MD ;)

**Comment by torch2424** [comment]
@julianpoy kidding! But yeah it does to be honest, I'm not entirely sure what this project is going to be. And I'm doing it in windows, so I have no clue how to use the GUI github haha! So I'll try when I figure things out. Like it literally took me a half hour to get this repo right. All these kids and their fancy Gui's these days haha!

**Comment by torch2424** [comment]
Creating this now...

**Comment by torch2424** [comment]
Finished just for @julianpoy via commit 0e1c22262828e2508b642e8b944ccb8a1ad98530
