### ISSUE TITLE
Add a Boss Theme

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#101]
What do ou think Of having a song start right when the boss is spawned, that way players know that the boss is coming, and should prepare accordingly? Also, it'd add to the atmosphere of the game!

**Comment by torch2424** [comment]
@heebe ?

**Comment by Heebe** [comment]
Agreed, the way it could be implemented would be like of Streets of Rage does it. Plus that idea makes me think immediately about something like this https://www.youtube.com/watch?v=ZQAXA0prSA0

**Comment by torch2424** [comment]
Dope, I got dis

**Comment by torch2424** [comment]
Made the main song faster, and finished the boss theme in FL. Going to code into the game now!

**Comment by torch2424** [comment]
Finished via b9b2afb69158350e8267e79273d21f422cc2fc4d I'm excited to see what you guys think of it, the song is much slower, but it matches the boss fights well in my opinion!
