### ISSUE TITLE
We Should Decide on how we will profit from the game...Includes some awesome talks

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#104]
It is important that we decide this now, as it could affect the way the game play dramatically in the future.

I think it should be offer a demo of just the core gameplay, and you can't unlock anything (kind of like a demo, but you can play forever). Since we are using Unity, we build a game one, and deploy anywhere, we can embed this game on it's own website, and our Dev Blog very easily, and use that to promote it. But through in app purchases, or buying the game, will you get the ability to unlock aesthetic games and stuff. For example, I suggest since their are 4 of us, we sell the game for about 2 - 5 bucks. Depending on how popular it gets and stuff like that. 

Or we can make the game COMPLETELY free, but to unlock the full game it costs the 2-5 bucks. This method is cool, but at the same time it's quite disappointing to the user. Either way, if unity allows us, we should definitely add character and map packs with things like new characters and maps, that we can sell for about a dollar each. We could also add something like new modes and things that can be unlocked with a mode pack or things. But for this game, I don't think we should go with a pay to win approach. 

Our other option is to make eveything in the game free, but use ads to make our revenue. Possibly after you lose 3-5 times an ad will appear on screen, and since our players are going to be constantly tpping, I'm sure it would work well. But in my previous experience ad revenue made barely anything for me. And I found it to not be worth it.

I'm honestly more in favor of the option of: Free web and mobile demos, but can buy the full version on desktop and mobile for somewhere between 2-5 bucks. With Map, DLC, and MOde packs being released in the future.

Also here is a reddit thread about games becoming popular: https://www.reddit.com/r/IndieDev/comments/3czw29/how_do_indie_games_like_crossy_road_become_so/

And within this I found an AWESOME talk from the guys who made crossy road (A mobile game I really enjoy playing, and is also made in unity), where they go over their development, but also How they planned on making money off of their game: http://www.gdcvault.com/play/1021897/Crossy-Road-A-Whale-of

P.s Character packs, every character could have a different special

**Comment by torch2424** [comment]
@heebe

**Comment by torch2424** [comment]
@emanuelpartida

**Comment by Heebe** [comment]
I like this idea "Free web and mobile demos, but can buy the full version on desktop and mobile for somewhere between 2-5 bucks. With Map, DLC, and MOde packs being released in the future." But let's put In-app adds into the demo for the mobile version. Implement them like Flappy Bird, the creator made 50k a day from just In-app adds only.

**Comment by Heebe** [comment]
I'm just not too sure if the "With Map, DLC, and MOde packs being released in the future" would sell very well though.

**Comment by torch2424** [comment]
Awesome I'm glad you agree on demos, I don't like the idea of ads though, in the case of banner ads I am hugely against, they make the least amount of money, and take up alot of real estate. Our other ad option at that point is iterestrials (Ads thart take up the whole screen we can have pop up when they die). But they are very annoying, and create huge drop off points. And to be honest, In my experiences, I've made wayyyy more from sales than ads in my previous apps. I've only made 20 bucks in ads compared to about the 300 i've made in the lifetime of my apps. we can use ads if you like, but just know the risk may not be worth the reward

And we don't neccesarily have to sell them. If anything, we can just give them in free updates of the game, it'll keep people coming back to play. And if we can implement in app purchases they will sell alright for the bigger dlcs

**Comment by Heebe** [comment]
Yeah, I don't think the ads are a good idea either, I was just pointing it out. But we should of course have a personal ad stating the benefits of buying the full game. What do you mean by "And if we can implement in app purchases they will sell alright for the bigger dlcs"?

**Comment by torch2424** [comment]
Ummm in app purchases are in games like crossy bird and stuff. Like when you go over a hidden character and it says buy for $.99. In my experience in app purchases didnt sell well for me, but I think the way I implemented them was bad.

And yes of course in the demo we can state buy the full game when you die or something @Heebe

**Comment by Heebe** [comment]
In-app purchases like that usually don't sell very well. Take some MMO's for instance, they get practically no revenue for things such as aesthetics.

**Comment by torch2424** [comment]
Are you sure? if you could, please provide some articles and statistics to prove that.

I've actually bought things such as new skateparks for true skate, and some other random IAPs in my time

**Comment by Heebe** [comment]
Actually, reading back on some things, times have changed. I was
referencing articles from mutiple years back but they aren't really
relevant now. Aesthetic in-game purchising would be fine as long as it
doesn't make it P2W. But it then also introduces the issue of what are we
going to use as "free dlc" and what we would be selling.

**Comment by torch2424** [comment]
@Heebe Yeah, and that's fine Wasn't planning on that.

THings like maps could be free dlc, as they are simply aesthetic. Or maybe multiplayer can come in an update.

But things like new characters that have more speed but less health could be an IAP (This is not P2W at all as you are simply buying a character with something you find more favorable, and keeps the game balanced). Or other random things like new bosses or possibly new modes like time attack or something random like that

**Comment by torch2424** [comment]
The beautiful things about modern day apps, is that they are always a work in progress, you dont have to stop developing them once they ship through the power of high speed ubiqutous internet

**Comment by Heebe** [comment]
Ok, that's cool.

**Comment by torch2424** [comment]
Finished and documented throug issue #120
