### ISSUE TITLE
Eye Color

### ISSUE THREAD

**Issue by Heebe** [torch2424/Fight#109]
When facing forward the character has brown eyes, but when he is running left or right, they are suddenly blue.

**Comment by torch2424** [comment]
FUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU

**Comment by torch2424** [comment]
Forsure thanks, it'll be a tedious fix but I'll get it done!

**Comment by torch2424** [comment]
Fixed via 387a00a61d7e2ab3f7f154d27fdc0affead5bf42

Took forever and was quite tedious
