### ISSUE TITLE
We Need to Choose which Characters/ art we want, and which ones we don't

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#111]
Since we are nearing a beat release, we need to start choosing which art we like and want to keep, and which can be tossed in room of newer/more polished characters

**Comment by emanuelpartida** [comment]
I updated the attack for eyeguy so it doesn't look like a Yoshi tongue...

**Comment by emanuelpartida** [comment]
I Updated the explosion animation!!!!!!!! It goes BOOOM!!!! cahahagdjashdiakjfakdlafd;ad;gksklvxcjkvcmzsdc,mlk;sm,zc;lzd,bv

**Comment by torch2424** [comment]
Rad sounds good dude! :D do you have any enemies you really like, and some you dnt care too much for? @emanuelpartida

**Comment by emanuelpartida** [comment]
I don't like spooky all that much...

**Comment by torch2424** [comment]
@emanuelpartida cool! I'll be sure to leave him out. I'm sorry to make you not use your own creations, we wanna have all of our favorite monsters you know?

**Comment by torch2424** [comment]
@emanuelpartida but I actually like spooky :'(

**Comment by emanuelpartida** [comment]
We could use Spooky as a Boss instead??

**Comment by torch2424** [comment]
@emanuelpartida sure that's be cool!

**Comment by torch2424** [comment]
Closing this and reopening as #134
