### ISSUE TITLE
Current Button Mapping

### ISSUE THREAD

**Issue by Heebe** [torch2424/Fight#112]
I think the button mapping as it stands right now is a little bit awkward too. It's a bit hard to play with ctrl but is playable with the wasd, r, and space combo, still a bit awkward though.

**Comment by torch2424** [comment]
any suggestions on controls

**Comment by torch2424** [comment]
@Heebe

**Comment by Heebe** [comment]
Roll could be 'B' and Special could be 'V'. That way it is comfortable for people who like arrow keys to move, and it would be comfortable for people using wasd too. Heck, even makes it possible for you to play the game with one hand even.

**Comment by torch2424** [comment]
Cool rad! I'm down for that.

But we still need to decide how specials will be done, issue #82 , but If we do decide to go with a button on a keyboard, it will be v.

**Comment by torch2424** [comment]
Fixing this now

**Comment by torch2424** [comment]
Finished via f4422e2fedc021dadd64c4b9170137cc48d4cf51
