### ISSUE TITLE
Idle Standing

### ISSUE THREAD

**Issue by Heebe** [torch2424/Fight#113]
There is no Idle standing. Let go of your controls and your character will keep walking in the direction you were last facing.

**Comment by torch2424** [comment]
@Heebe yes I noticed that too, but I didnt think it was that serious, I can make him not move though. Also, are you okay with the running in place animation for not moving? I feel like it is quite standard to have that

**Comment by Heebe** [comment]
Why? I think it seems sloppy. If he stands in one place he should have a
standing animation.

**Comment by torch2424** [comment]
K, wel I'll go and add the animation state for that and stuff

**Comment by torch2424** [comment]
Doing this now, get the animation for the characters folder

**Comment by torch2424** [comment]
Finished the standing still, but the idle is going to be super difficult

**Comment by torch2424** [comment]
Finished via 02e83b122ed1f01b2dc7352a7c75ff16f0cd7d27
