### ISSUE TITLE
Unstable?

### ISSUE THREAD

**Issue by Heebe** [torch2424/Fight#118]
The game becomes more unstable the more you level. I noticed both lag showing up, and, well, this happened when I died at lvl 33.
![super punch master kevin](https://cloud.githubusercontent.com/assets/7026914/9243632/ab0e2066-4147-11e5-8eaf-f2550e601a13.png)

**Comment by torch2424** [comment]
Damn how'd you get to level 33? HAHAHAHAHA! it's cause our death messages look like this:

//Array pf things to say once you die
    String[] epitaph = {"Even the mighty fall", "Not even heroes live forever", "Legends are never forgotten"};

If you notice, there's only 3, so we need more. I'll code a failsafe right now, and I created this issue: #119

And It'd be cool if you could write some more

**Comment by torch2424** [comment]
Fixed via 1da3dba284ad1e11e7e7932f886771e762e34c7c
