### ISSUE TITLE
Add our new background

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#13]
It also awesome :D

**Comment by torch2424** [comment]
@Heebe I'm going to remove this from the milestone for alpha 1.0, since It's quite a bit of work to remove all the tiles I had in the game, and resize all of my colliders to fit the maps you have presented

**Comment by torch2424** [comment]
Alos, would you rather have the forest or the mountains in the build after?

**Comment by torch2424** [comment]
Actually, hmmm I'll try for the alpha, but no promises, but still which would you like first?

**Comment by Heebe** [comment]
Definitely the forest.

**Comment by torch2424** [comment]
Fashowty my dude :D @Heebe

**Comment by torch2424** [comment]
![image](https://cloud.githubusercontent.com/assets/1448289/7671854/8987f654-fc93-11e4-90e5-b44b5d62b38a.png)

Added our map. SInce it was smaller than the last one, I had to readjust all of the speed, character bounds, and camera bound values .

Later we can implement multiple maps and things in a new issue
