### ISSUE TITLE
Out of bounds

### ISSUE THREAD

**Issue by Heebe** [torch2424/Fight#131]
Bug just recently found: If you pause the game from spawn and mash the punch key, the punch still registers and pushes the player forward, this motion allows the player to phase out of the map completely.
![untitled](https://cloud.githubusercontent.com/assets/7026914/9323637/7e4572b6-4537-11e5-8686-53f9c282bb8b.png)
![untitled2](https://cloud.githubusercontent.com/assets/7026914/9323636/7e44a188-4537-11e5-9d95-00a0fb4ba2db.png)
![untitled3](https://cloud.githubusercontent.com/assets/7026914/9323638/7e46a47e-4537-11e5-9e60-b563a449ecc7.png)

**Comment by torch2424** [comment]
HAHAHAHAHAHAHA YESSSSSSSSS

**Comment by torch2424** [comment]
thank you

**Comment by torch2424** [comment]
Fixed via cc3e0277d0510bf8e8f85dd0c93584d0c30e4166
