### ISSUE TITLE
Idea: Show Score

### ISSUE THREAD

**Issue by Heebe** [torch2424/Fight#138]
Maybe show score obtained, onto the death screen above the options buttons like shown in this picture. It will add a little more focus on the score overall.
![untitled3](https://cloud.githubusercontent.com/assets/7026914/9454080/37bc4e86-4a74-11e5-9def-b304bc9115db.png)

**Comment by torch2424** [comment]
Oh yeah I totally forgot about that when I added score hahahaha! thank you!

**Comment by torch2424** [comment]
This was fixed by #139
