### ISSUE TITLE
No windowed mode scaling

### ISSUE THREAD

**Issue by Heebe** [torch2424/Fight#139]
When trying to play the game on a lower resolution in windowed mode, the game will not scale. (i.e. the Map selection and the character selection options will be gone. Shown here ▼. It will also cut off score and the word "health" while in gameplay.)
**What it does:**
![doesntscale](https://cloud.githubusercontent.com/assets/7026914/9554364/26d85a8e-4d7a-11e5-94b1-57b1a94c72f2.png)
**What is being cut off**
![whatitshouldbe](https://cloud.githubusercontent.com/assets/7026914/9554471/0c73c36c-4d7b-11e5-981f-f818d7a4ef33.png)

**Comment by torch2424** [comment]
Yeah the scaling is quite difficult in the game, I'll look into it

**Comment by torch2424** [comment]
Fixed game scaling depending on screensize, going to look into windowed mode scaling c6fd18578721e16b0eb1e0110b1ca96e1a392dbd

**Comment by torch2424** [comment]
Actually, if you notice, you can choose a resolution when the game starts for the size of the window. We do not want out users to scale our windows, that is why unity defaults it to not scalable. scaling the window while the game is playing will break all of the scaling of the game, and ruin everything. I just rembered I made another game for a class, and they told me part of the requirements was making it unscalable. this is now finished
