### ISSUE TITLE
This Game needs an official title!

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#16]
I mean Fight! is cool and all, but a real name would be nice wouldn't it? Haha

**Comment by torch2424** [comment]
@Heebe Yeah cool yo. Hey, I think we should all agree upon a name for the game before I do the title screen and everybody shoul have a say in it. Emanuel likes the names Fight to the Death, or, Path to Victory. I like Might Within, or just, Might. What do you think would be a good name?

**Comment by torch2424** [comment]
Lets call it Beat EM UP!!! Punch Legacy, Fist Legacy
I like Punch legacy the most
Maybe fist story, or fight story
I did some googling, nintendo suggests that you name the game what it is. such as the legend of zelda, or super mario

**Comment by Heebe** [comment]
It's unanimous, Punch Legacy.

**Comment by torch2424** [comment]
@Heebe rad! I'll wpork on this in a bit. Work has been killing me :/
