### ISSUE TITLE
Enemies can ovverun the game and push you through the walls

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#2]
One suggestion is to make enemies not move if you are touching a wall, that way, if you are surrounded they will still attack

**Comment by Heebe** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7026914/7659134/ac18a65a-faf4-11e4-878c-a07671fb5fc5.png)
Busted through a wall and got the development console to open up

**Comment by torch2424** [comment]
HAhahahahahahahahaha This game is highlarious. Yo I had the idea of making it so that enemys will no longer move if your touching a wall, but that creates the problem of enemies just standing there instead of coming after you.

**Comment by torch2424** [comment]
I'll come back to this issue after thinking what I can do about it later.Hopefully with the new enemy cap, this is less likely to happen, and I feel like we should test this more now that that issue has been addressed

**Comment by torch2424** [comment]
@Heebe I need to you test this with the new alpha build, enemies kill me before I can even see this happening. Can you duplicate this on the newest builds? This is the last "major" thing holding us back from moving forward with a new alpha

**Comment by Heebe** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7026914/7741852/75413ad0-ff3a-11e4-99b5-cd9d9cb6a9ea.png)
I would like to, but the camera doesn't pan with me to the edge if the screen to even test this. I'm at a 1920 x 1200 resolution if that helps. Anyway, if you can't tell from the screenshot, I'm over to the right side of the screen. Happens on the left side as well.

**Comment by torch2424** [comment]
@Heebe I'll fix that right now, I just make the colliders too close haha!

**Comment by torch2424** [comment]
Oh it's actually something I'll have to code it, Here's a build you can see the edge no matter what, and I addressed the issue in #27

Build: https://www.dropbox.com/s/dn2b6sm5wz6xy1n/Alpha%201.1.zip?dl=0

**Comment by Heebe** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7026914/7760145/3b6f241e-ffcd-11e4-843d-3724b846428f.png)
It's extremely hard to replicate the bug now that enemies can't be hit from behind. This is the highest level I can even reach, so I'd say you already fixed this problem.

**Comment by torch2424** [comment]
Alright cool! If anything this issue can be reopened and done again later!
