### ISSUE TITLE
Zoom out the camera a bit!

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#21]
The new game scale is too small and enemies fly on screen way to fast, need to zoom out our camera a bit haha!

**Comment by Heebe** [comment]
Could this be because of the map itself being so small? It's only set up in
a 400 x 400 scale.

**Comment by torch2424** [comment]
Naw It's my camera dude dont worry, it's just a number i change haha! and I fixed in this commit c0bcba8cfd3373ae864d3a364218d609cfbc68d2

**Comment by torch2424** [comment]
@Heebe
