### ISSUE TITLE
Sounds play other than the hit sound after you have died

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#25]
Need to stop enemy attack sounds from playing after we die

**Comment by Heebe** [comment]
Could fix by muting all other sounds and playing only a "death theme".

**Comment by torch2424** [comment]
Naw thats not how the code is set up haha! @Heebe

**Comment by torch2424** [comment]
But I fixed it, now only the death sound will play after game over via 62f4be3f000fb10ab692171424f0ec00f8c11c8b

**Comment by torch2424** [comment]
But I fixed it, now only the death sound will play after game over via 62f4be3f000fb10ab692171424f0ec00f8c11c8b
