### ISSUE TITLE
Attacking forward also hurts enemies behind you

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#3]
Try finiding an enemy's position relative to the way you are facing, if behind you, do no damage

**Comment by Heebe** [comment]
After done, issue must be addressed where if you spam the attack button, the character stays facing that exact orientation. As you keep pressing attack and move the character around, the character slides around forward, back, side-to-side always in that orientation until attacking has ceased.

**Comment by torch2424** [comment]
Ye ye ye, I actually tried to fix this, but the unity animator is a weird beast haha

**Comment by torch2424** [comment]
@Heebe

**Comment by torch2424** [comment]
No longer can attack enemies generally around you, And I mess with the animator a couple of commits ago, and what @Heebe has stated is fixed as well. As of this commit, this issue is closed 9e169252055ea13cba9c9d273804f2700738619f
