### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by Heebe** [torch2424/Fight#33]
![untitled](https://cloud.githubusercontent.com/assets/7026914/8026542/597dbaf0-0d2f-11e5-8818-b9aa7f145bdb.png)
Seems like if you stand in the corner and spam the space bar you can easily take out enemies and level up, making the game very easy. Along with this, once enough enemies spawn, they cluster and wont even try and run at you.

_found by Emanuel, retested by me_

**Comment by torch2424** [comment]
Oh yeah I fixed that yo

**Comment by torch2424** [comment]
@Heebe See issue #24 , I'm closing this
