### ISSUE TITLE
Add some camera kick (Feel)

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#41]
Like screenshake, but move camera opposite of player when were attacking, and when we collide with an attack, shake the screen

**Comment by Heebe** [comment]
Move it forward instead of back? Might give the illusion that you hit hard as hell.

**Comment by torch2424** [comment]
I've been on the fence about this issue. I feel like we should keep screenshake to attacks and when damage is dealt. as we do not want to confuse the player, and or have too much screenshake, as I feel like we are getting close to that threshold.

Closing this now
