### ISSUE TITLE
We should all watch some good game talks

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#42]
Vlambeer guy -
https://www.youtube.com/watch?v=kgYpJpbpnZI

Vlambeer guy (Screenshake)
https://www.youtube.com/watch?v=AJdEqssNZ-U

Secrets of game fuel and juice
https://www.youtube.com/watch?v=216_5nu4aVQ

**Comment by torch2424** [comment]
@Heebe

**Comment by Heebe** [comment]
Watched all three.

**Comment by Heebe** [comment]
One by Vlambeer that talks more about how he and his friend got to the point in their lives, it works great after watching the ones you posted because it elaborates with them pretty well.
https://www.youtube.com/watch?v=JER2Wlu64AY

**Comment by Heebe** [comment]
Why is this set as a milestone?

**Comment by torch2424** [comment]
Everyine watched some good game talks heres the last one I mentioned on game marketing!

https://www.youtube.com/watch?v=SkEQtMP2CuA
