### ISSUE TITLE
Have rounds of spawning With Bosses in between

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#44]
Instead of constant spawnin, how about after every 30 enemies spawn, stop for about a minute, to give the player a breather

Suggested by my buddy Julian @julianpoy Because his little bitty lady fingers hurt

**Comment by Heebe** [comment]
a minute is quite long

**Comment by torch2424** [comment]
Forsure @Heebe I'll just mess around with the values, maybe like 30 seconds? I'll figure it out!

**Comment by torch2424** [comment]
With bosses in between

**Comment by torch2424** [comment]
Going to Save this for another alpha, since this will work with bosses

**Comment by torch2424** [comment]
Starting this now

**Comment by torch2424** [comment]
This is finished, I just need to scale the bosses stats accordingly

**Comment by torch2424** [comment]
a6909f6b579b762e6ca36a7464343d6adfdf01a0

The commit above is the point where bosses are fully inputted into the game, heres a screenshot: 
<img width="709" alt="boss" src="https://cloud.githubusercontent.com/assets/1448289/8760099/eb15aa14-2cbe-11e5-88b8-2f7a77c3ed97.png">

And also, here is a .gif of me celebrating

![selfie-0](http://i.imgur.com/fjfLGlH.gif)
