### ISSUE TITLE
Add obstacles to our map

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#47]
So that players can use strategy to trap enemies and play around them

**Comment by torch2424** [comment]
@heebe I need you and emanual to do art for this

**Comment by Heebe** [comment]
Suggestions?

**Comment by torch2424** [comment]
Going to be randomly placed onto map

**Comment by torch2424** [comment]
Starting this now

**Comment by torch2424** [comment]
Almost finished gotta bug fix!

**Comment by torch2424** [comment]
Finished, and working great! Need to add more object images, and scale/Stop them from moving

via 914348ea9bde06e623f8d060a8aa035b10b71b7c
