### ISSUE TITLE
Story

### ISSUE THREAD

**Issue by Heebe** [torch2424/Fight#48]
There should be a segment of text or screen that appears after you press start, to introduce a "story" that helps the player understand why it's a "Punch Legacy". This may work great considering we have messages that follow something of feeling after the player dies. I have written up a few short messages that should be reviewed by @torch2424 so we can choose the best one.

edit: I'll email them once I know this has been seen.

**Comment by torch2424** [comment]
Got the email and will try to add in next alpha

**Comment by torch2424** [comment]
![image](https://cloud.githubusercontent.com/assets/1448289/8147491/1bc72dca-1222-11e5-8061-338f39f65db5.png)

Finished via bfa8d85df578c8a6d9547f47079e5c07db5fe419
