### ISSUE TITLE
Add Camera "Lerp"

### ISSUE THREAD

**Issue by Heebe** [torch2424/Fight#50]
Again as stated in https://www.youtube.com/watch?v=AJdEqssNZ-U Lag the camera behind the character so it feels as if you are controlling it all, other than just the character. It will make the game feel much better and show the player how much faster and more powerful you have gotten.

**Comment by torch2424** [comment]
Already did in alpha 3.0, closing this see issue #20

**Comment by Heebe** [comment]
It's not very apparent at all then

**Comment by torch2424** [comment]
Resolved through text message with @Heebe
