### ISSUE TITLE
Add Big D Sounds to game

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#59]
Re recorded, and sound good!

**Comment by torch2424** [comment]
Sounding amazing, shout out to big d!

0b41ef954a45dfeb04e0def3db01af2881622e64

![image](https://cloud.githubusercontent.com/assets/1448289/8389535/d3925bc4-1c26-11e5-8b85-211c864e2cfb.png)

**Comment by Heebe** [comment]
We're officially super now?

**Comment by torch2424** [comment]
ye :dancers:

**Comment by Heebe** [comment]
Alright, want me to make the art for the "Super" now then?

**Comment by torch2424** [comment]
@Heebe Yeeeeee, also check the github main page I made it dope
