### ISSUE TITLE
We need a game start menu!

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#6]
MAke a game start menu where it starts the music, and you press a button to play!

**Comment by torch2424** [comment]
@Heebe I'm planning on making the game start menu all black an nostalgic like this, I feel like it'll really match the feel of the game

![](http://static.giantbomb.com/uploads/original/1/13084/364148-dig_dug_2008_07_29_00_22_21_59.png)

![](http://www.nesgametabs.com/images/online%20game%20links/Mega_Man1title.png)

![](http://www.consoleclassix.com/info_img/Contra_NES_ScreenShot1.jpg)

**Comment by Heebe** [comment]
This is a great idea, I just can't yet start this without an official title. We should all have a say in it.

**Comment by torch2424** [comment]
@Heebe I'm going to start this later without the title graphic as It'd be VERY easy to just throw into our start menu, that way I can get started and finish our alpha

**Comment by Heebe** [comment]
Ok yeah that's cool, it'll be done by tomorrow night

**Comment by torch2424** [comment]
![image](https://cloud.githubusercontent.com/assets/1448289/7695088/22fcb23c-fd9f-11e4-97b9-9088007efd7a.png)

Fully working, we need to plug in our logo and things later, but for now we have the funnctionality dso the issues is closed  via 6bf7250bec23bd23c8ecfcbe0887527ad0f57219
