### ISSUE TITLE
Aspect Ration is off with resolution

### ISSUE THREAD

**Issue by Heebe** [torch2424/Fight#76]
For this screen, (1920x1080)
![aspectratio](https://cloud.githubusercontent.com/assets/7026914/8269329/d8c30210-1758-11e5-8903-82fe3f465edc.png)

**Comment by torch2424** [comment]
I don't see the problem, you want it to be bigger or what?

**Comment by Heebe** [comment]
*Ratio, and I think they should be centered and not so far apart, like this.
![aspectratio](https://cloud.githubusercontent.com/assets/7026914/8273523/66c2183a-1826-11e5-887e-365e9c0b0a82.png)

**Comment by Heebe** [comment]
Otherwise the huge gap between the lettering on one side of the screen and the character on the other looks awful.

**Comment by torch2424** [comment]
Fashow, I can work on that

**Comment by torch2424** [comment]
Fixed via the inspector in 72ae379108e4fe7193d79377faf76d8965aeb65d
