### ISSUE TITLE
Objects Kill

### ISSUE THREAD

**Issue by Heebe** [torch2424/Fight#77]
When enemies collide with an object, for this instance the boulder, they have a chance for dieing. I had  a group chasing me and right when one walked into the object he exploded and killed the rest of the group.

**Comment by torch2424** [comment]
Hahaha that's dope. I think it's cause I coded that if they are in knockback and they hit a wall (such as an object) they lose one health. Were they in knockback? I might have to forgot to add a simple && to a conditional

**Comment by Heebe** [comment]
They weren't in knockback. The enemy was just following me and blew up when
he touched the object.

**Comment by torch2424** [comment]
Forsure I can fix that with some simple bools

**Comment by torch2424** [comment]
Fixed with only 13 characters in 0b7b3d2b80eff5093b9cbc4ac68065b03b3e02c7
