### ISSUE TITLE
Make Explosions Smaller?

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#78]
After Alpha 5.0 is distributed, Big D suggested smaller exlposions, let me know of this!

**Comment by torch2424** [comment]
@Heebe What do you think of this?

**Comment by torch2424** [comment]
I feel like they're sized nicely

**Comment by Heebe** [comment]
With the new explosion animation, they should be fine, it depends when I see it though.

**Comment by torch2424** [comment]
K

**Comment by torch2424** [comment]
@Heebe was referring #110

**Comment by torch2424** [comment]
Finished via 387a00a61d7e2ab3f7f154d27fdc0affead5bf42
