### ISSUE TITLE
We should consider Health Regenerate when not punching

### ISSUE THREAD

**Issue by torch2424** [torch2424/Fight#88]
I think this is a good idea, as it'll give players a reason to run away. That way if they can skillfully dodge or run, while avoiding enemies, we should reward them for this. Also, if they are attacking they should not regenerate health. This is another reason for them not to just spam the space bar

**Comment by Heebe** [comment]
I agree

**Comment by torch2424** [comment]
@Heebe  <3

**Comment by torch2424** [comment]
Working on this now

**Comment by torch2424** [comment]
Finished and preety cool via 11413619aac514eecd574d37d5af3c3639c001df
