### ISSUE TITLE
Major lag with enemy clusters

### ISSUE THREAD

**Issue by Heebe** [torch2424/Fight#9]
If enough enemies spawn, cluster, and smash you in a corner, there is no way to get yourself out of it. As soon as you rush in and try to fight, the lag hits hard and you can instantly die.

edit: reached lvl 23 and the enemy number became so great the lag hit hugely no matter what.

**Comment by torch2424** [comment]
DAMMMMNNNNNN YOU GOT TO LEVEL 23?!?!?!??! I can't make it past 18 haha!

**Comment by torch2424** [comment]
But yo, I'll just keep count of the number of enemies, could you guesstimate how many enemies were spawned? I can just create a static variable in the enemy class, and once so many are created, don't create any more

**Comment by Heebe** [comment]
Try capping at 200 and I'll test until we have the right number.

**Comment by torch2424** [comment]
Yo 200 is way too much haha! I'll try 50! if anything, if you look through the code, i can make it so that the enemy attack frames lower as they become higher level, so essentially, they'll start goiing through your health like nothing, but 50 still looks like a gang of enemies @Heebe

**Comment by torch2424** [comment]
Capped it at 75, tested and fixed via cd3d21384dc885ad0874b2a97decd94fa1b30496

**Comment by torch2424** [comment]
Wrong Ssh this is the right one haha 7031f7e475f5cff9df506933136887c40eae25e9

**Comment by Heebe** [comment]
cap at 70, lag is still there trying to render all enemies on the screen.
