### ISSUE TITLE
Old man for Intro

### ISSUE THREAD

**Issue by emanuelpartida** [torch2424/Fight#96]
i was thinking instead of punch guy in the intro there could be an old man???

**Comment by torch2424** [comment]
I'm down for dat :D

**Comment by torch2424** [comment]
Fixed via a669a757e07868b0d467fb95175e3a94fd7b81ef

![image](https://cloud.githubusercontent.com/assets/1448289/8760286/803f9b06-2cc7-11e5-9b4e-a69f97e5e563.png)
